[package]
name = "rusteroids"
version = "0.1.0"
edition = "2021"

[dependencies]
specs = { version = "*" }
specs-derive = { version = "*" }
vector2d = { version = "*" }
rand = { version = "*" }
once_cell = "*"
kira = { version = "*" }

[dependencies.sdl2]
version = "*"
features = ["image","ttf"]
