uint16_t colors[] = {  // no need to swap
0xdff7,	// TFT_ALICEBLUE
0x5aff,	// TFT_ANTIQUEWHITE
0xff07,	// TFT_AQUA
0xfa7f,	// TFT_AQUAMARINE
0xfff7,	// TFT_AZURE
0xbbf7,	// TFT_BEIGE
0x38ff,	// TFT_BISQUE
0x0000,	// TFT_BLACK
0x59ff,	// TFT_BLANCHEDALMOND
0x1f00,	// TFT_BLUE
0x5c89,	// TFT_BLUEVIOLET
0x45a1,	// TFT_BROWN
0xd0dd,	// TFT_BURLYWOOD
0xf45c,	// TFT_CADETBLUE
0xe07f,	// TFT_CHARTREUSE
0x43d3,	// TFT_CHOCOLATE
0xeafb,	// TFT_CORAL
0xbd64,	// TFT_CORNFLOWERBLUE
0xdbff,	// TFT_CORNSILK
0xa7d8,	// TFT_CRIMSON
0xff07,	// TFT_CYAN
0x1100,	// TFT_DARKBLUE
0xef03,	// TFT_DARKCYAN
0x5104,	// TFT_DARKCYAN2
0x21bc,	// TFT_DARKGOLDENROD
0x55ad,	// TFT_DARKGRAY
0x2003,	// TFT_DARKGREEN2
0xe003,	// TFT_DARKGREEN
0xef7b,	// TFT_DARKGREY
0xadbd,	// TFT_DARKKHAKI
0x1188,	// TFT_DARKMAGENTA
0x4553,	// TFT_DARKOLIVEGREEN
0x60fc,	// TFT_DARKORANGE
0x9999,	// TFT_DARKORCHID
0x0088,	// TFT_DARKRED
0xafec,	// TFT_DARKSALMON
0xf18d,	// TFT_DARKSEAGREEN
0xf149,	// TFT_DARKSLATEBLUE
0x692a,	// TFT_DARKSLATEGRAY
0x7a06,	// TFT_DARKTURQUOISE
0x1a90,	// TFT_DARKVIOLET
0xb2f8,	// TFT_DEEPPINK
0xff05,	// TFT_DEEPSKYBLUE
0x4d6b,	// TFT_DIMGRAY
0x9f1c,	// TFT_DODGERBLUE
0x04b1,	// TFT_FIREBRICK
0xdeff,	// TFT_FLORALWHITE
0x4424,	// TFT_FORESTGREEN
0x1ff8,	// TFT_FUCHSIA
0xfbde,	// TFT_GAINSBORO
0xdfff,	// TFT_GHOSTWHITE
0xa0fe,	// TFT_GOLD
0x24dd,	// TFT_GOLDENROD
0x1084,	// TFT_GRAY
0x0004,	// TFT_GREEN2
0xe007,	// TFT_GREEN
0xe5af,	// TFT_GREENYELLOW
0xfef7,	// TFT_HONEYDEW
0x56fb,	// TFT_HOTPINK
0xebca,	// TFT_INDIANRED
0x1048,	// TFT_INDIGO
0xfeff,	// TFT_IVORY
0x31f7,	// TFT_KHAKI
0x3fe7,	// TFT_LAVENDER
0x9eff,	// TFT_LAVENDERBLUSH
0xe07f,	// TFT_LAWNGREEN
0xd9ff,	// TFT_LEMONCHIFFON
0xdcae,	// TFT_LIGHTBLUE
0x10f4,	// TFT_LIGHTCORAL
0xffe7,	// TFT_LIGHTCYAN
0xdaff,	// TFT_LIGHTGOLDENRODYELLOW
0x7297,	// TFT_LIGHTGREEN
0x18c6,	// TFT_LIGHTGREY
0x9ad6,	// TFT_LIGHTGREY2
0xb8fd,	// TFT_LIGHTPINK
0x0ffd,	// TFT_LIGHTSALMON
0x9525,	// TFT_LIGHTSEAGREEN
0x7f86,	// TFT_LIGHTSKYBLUE
0x5374,	// TFT_LIGHTSLATEGRAY
0x3bb6,	// TFT_LIGHTSTEELBLUE
0xfcff,	// TFT_LIGHTYELLOW
0xe007,	// TFT_LIME
0x6636,	// TFT_LIMEGREEN
0x9cff,	// TFT_LINEN
0x1ff8,	// TFT_MAGENTA
0x0078,	// TFT_MAROON
0x0080,	// TFT_MAROON2
0x7566,	// TFT_MEDIUMAQUAMARINE
0x1900,	// TFT_MEDIUMBLUE
0xbaba,	// TFT_MEDIUMORCHID
0x9b93,	// TFT_MEDIUMPURPLE
0x8e3d,	// TFT_MEDIUMSEAGREEN
0x5d7b,	// TFT_MEDIUMSLATEBLUE
0xd307,	// TFT_MEDIUMSPRINGGREEN
0x994e,	// TFT_MEDIUMTURQUOISE
0xb0c0,	// TFT_MEDIUMVIOLETRED
0xce18,	// TFT_MIDNIGHTBLUE
0xfff7,	// TFT_MINTCREAM
0x3cff,	// TFT_MISTYROSE
0x36ff,	// TFT_MOCCASIN
0xf5fe,	// TFT_NAVAJOWHITE
0x0f00,	// TFT_NAVY
0x1000,	// TFT_NAVY2
0xbcff,	// TFT_OLDLACE
0xe07b,	// TFT_OLIVE
0x0084,	// TFT_OLIVE2
0x646c,	// TFT_OLIVEDRAB
0x20fd,	// TFT_ORANGE
0x20fa,	// TFT_ORANGERED
0x9adb,	// TFT_ORCHID
0x55ef,	// TFT_PALEGOLDENROD
0xd39f,	// TFT_PALEGREEN
0x7daf,	// TFT_PALETURQUOISE
0x92db,	// TFT_PALEVIOLETRED
0x7aff,	// TFT_PAPAYAWHIP
0xd7fe,	// TFT_PEACHPUFF
0x27cc,	// TFT_PERU
0x1ff8,	// TFT_PINK
0x19fe,	// TFT_PINK_2
0x1bdd,	// TFT_PLUM
0x1cb7,	// TFT_POWDERBLUE
0x0f78,	// TFT_PURPLE
0x1080,	// TFT_PURPLE2
0x00f8,	// TFT_RED
0x71bc,	// TFT_ROSYBROWN
0x5c43,	// TFT_ROYALBLUE
0x228a,	// TFT_SADDLEBROWN
0x0efc,	// TFT_SALMON
0x2cf5,	// TFT_SANDYBROWN
0x4a2c,	// TFT_SEAGREEN
0xbdff,	// TFT_SEASHELL
0x85a2,	// TFT_SIENNA
0x18c6,	// TFT_SILVER
0x7d86,	// TFT_SKYBLUE
0xd96a,	// TFT_SLATEBLUE
0x1274,	// TFT_SLATEGRAY
0xdfff,	// TFT_SNOW
0xef07,	// TFT_SPRINGGREEN
0x1644,	// TFT_STEELBLUE
0xb1d5,	// TFT_TAN
0x1004,	// TFT_TEAL
0xfbdd,	// TFT_THISTLE
0x08fb,	// TFT_TOMATO
0x1a47,	// TFT_TURQUOISE
0x1dec,	// TFT_VIOLET
0xf6f6,	// TFT_WHEAT
0xffff,	// TFT_WHITE
0xbef7,	// TFT_WHITESMOKE
0xe0ff,	// TFT_YELLOW
0x669e	// TFT_YELLOWGREEN
};



#define TFT_ALICEBLUE            0
#define TFT_ANTIQUEWHITE         1
#define TFT_AQUA                 2
#define TFT_AQUAMARINE           3
#define TFT_AZURE                4
#define TFT_BEIGE                5
#define TFT_BISQUE               6
#define TFT_BLACK                7
#define TFT_BLANCHEDALMOND       8
#define TFT_BLUE                 9
#define TFT_BLUEVIOLET           10
#define TFT_BROWN                11
#define TFT_BURLYWOOD            12
#define TFT_CADETBLUE            13
#define TFT_CHARTREUSE           14
#define TFT_CHOCOLATE            15
#define TFT_CORAL                16
#define TFT_CORNFLOWERBLUE       17
#define TFT_CORNSILK             18
#define TFT_CRIMSON              19
#define TFT_CYAN                 20
#define TFT_DARKBLUE             21
#define TFT_DARKCYAN             22
#define TFT_DARKCYAN2            23
#define TFT_DARKGOLDENROD        24 
#define TFT_DARKGRAY             25
#define TFT_DARKGREEN2           26
#define TFT_DARKGREEN            27
#define TFT_DARKGREY             28
#define TFT_DARKKHAKI            29
#define TFT_DARKMAGENTA          30
#define TFT_DARKOLIVEGREEN       31 
#define TFT_DARKORANGE           32
#define TFT_DARKORCHID           33
#define TFT_DARKRED              34
#define TFT_DARKSALMON           35 
#define TFT_DARKSEAGREEN         36 
#define TFT_DARKSLATEBLUE        37
#define TFT_DARKSLATEGRAY        38
#define TFT_DARKTURQUOISE        39
#define TFT_DARKVIOLET           40
#define TFT_DEEPPINK             41
#define TFT_DEEPSKYBLUE          42 
#define TFT_DIMGRAY              43
#define TFT_DODGERBLUE           44 
#define TFT_FIREBRICK            45
#define TFT_FLORALWHITE          46
#define TFT_FORESTGREEN          47
#define TFT_FUCHSIA              48
#define TFT_GAINSBORO            49
#define TFT_GHOSTWHITE           50
#define TFT_GOLD                 51
#define TFT_GOLDENROD            52   
#define TFT_GRAY                 53
#define TFT_GREEN2               54
#define TFT_GREEN                55
#define TFT_GREENYELLOW          56
#define TFT_HONEYDEW             57
#define TFT_HOTPINK              58
#define TFT_INDIANRED            59
#define TFT_INDIGO               60
#define TFT_IVORY                61
#define TFT_KHAKI                62
#define TFT_LAVENDER             63
#define TFT_LAVENDERBLUSH        64    
#define TFT_LAWNGREEN            65
#define TFT_LEMONCHIFFON         66 
#define TFT_LIGHTBLUE            67
#define TFT_LIGHTCORAL           68
#define TFT_LIGHTCYAN            69
#define TFT_LIGHTGOLDENRODYELLOW 70
#define TFT_LIGHTGREEN           71
#define TFT_LIGHTGREY            72
#define TFT_LIGHTGREY2           73
#define TFT_LIGHTPINK            74
#define TFT_LIGHTSALMON          75
#define TFT_LIGHTSEAGREEN        76
#define TFT_LIGHTSKYBLUE         77
#define TFT_LIGHTSLATEGRAY       78
#define TFT_LIGHTSTEELBLUE       79
#define TFT_LIGHTYELLOW          80
#define TFT_LIME                 81
#define TFT_LIMEGREEN            82
#define TFT_LINEN                83
#define TFT_MAGENTA              84
#define TFT_MAROON               85
#define TFT_MAROON2              86
#define TFT_MEDIUMAQUAMARINE     87
#define TFT_MEDIUMBLUE           88
#define TFT_MEDIUMORCHID         89
#define TFT_MEDIUMPURPLE         90
#define TFT_MEDIUMSEAGREEN       91
#define TFT_MEDIUMSLATEBLUE      92
#define TFT_MEDIUMSPRINGGREEN    93
#define TFT_MEDIUMTURQUOISE      94
#define TFT_MEDIUMVIOLETRED      95
#define TFT_MIDNIGHTBLUE         96
#define TFT_MINTCREAM            97
#define TFT_MISTYROSE            98
#define TFT_MOCCASIN             99
#define TFT_NAVAJOWHITE          100
#define TFT_NAVY                 101
#define TFT_NAVY2                102
#define TFT_OLDLACE              103
#define TFT_OLIVE                104
#define TFT_OLIVE2               105
#define TFT_OLIVEDRAB            106
#define TFT_ORANGE               107
#define TFT_ORANGERED            108
#define TFT_ORCHID               109
#define TFT_PALEGOLDENROD        110
#define TFT_PALEGREEN            111
#define TFT_PALETURQUOISE        112
#define TFT_PALEVIOLETRED        113
#define TFT_PAPAYAWHIP           114
#define TFT_PEACHPUFF            115
#define TFT_PERU                 116
#define TFT_PINK                 117
#define TFT_PINK_2               118
#define TFT_PLUM                 119
#define TFT_POWDERBLUE           120
#define TFT_PURPLE               121
#define TFT_PURPLE2              122
#define TFT_RED                  123
#define TFT_ROSYBROWN            124
#define TFT_ROYALBLUE            125
#define TFT_SADDLEBROWN          126
#define TFT_SALMON               127
#define TFT_SANDYBROWN           128
#define TFT_SEAGREEN             129
#define TFT_SEASHELL             130
#define TFT_SIENNA               131
#define TFT_SILVER               132
#define TFT_SKYBLUE              133
#define TFT_SLATEBLUE            134
#define TFT_SLATEGRAY            135
#define TFT_SNOW                 136
#define TFT_SPRINGGREEN          137
#define TFT_STEELBLUE            138
#define TFT_TAN                  139
#define TFT_TEAL                 140
#define TFT_THISTLE              141
#define TFT_TOMATO               142
#define TFT_TURQUOISE            143
#define TFT_VIOLET               144
#define TFT_WHEAT                145
#define TFT_WHITE                146
#define TFT_WHITESMOKE           147
#define TFT_YELLOW               148
#define TFT_YELLOWGREEN          149  
 

