***** chit placement
3:C1:F
11:A5:F
14:AA5:F
14:P15:F
15:AA15:F
9:AA16:B
3:B15:B

***** set embarkable
this trigger is for the program


***** END
**************************************************************** Notes
^[0-9]+        : chit ID
[A-Z]+[0-9]+   : hex ID
[FB]$          : (F)ront side or (B)ack side of chit

********** flags
bit
0:    chit's side (F=0; B=1)
1:    unit is SHAKEN
2:    unit has FIRED
3:    unit has MOVED


create table chit_status (
   id      int,
   chit_ID int,
   hex_ID  varchar(80),
   flags   int
);

https://github.com/JakubSzark/zig-string
